// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SternGarages.Data;

#nullable disable

namespace SternGarage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SternGarage.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Horsepower")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Cars", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            CreatedAt = new DateTime(2026, 2, 16, 9, 54, 45, 78, DateTimeKind.Utc).AddTicks(3039),
                            Description = "C-Class комбинира спортен дизайн с технологии. 2.0L турбо с 48V mild hybrid дава 255 к.с. плюс допълнителни 20 к.с. при нужда. MBUX система, 9-степенна автоматична скоростна кутия.",
                            EngineType = "2.0L Turbo Бензин + 48V Mild Hybrid",
                            Horsepower = 255,
                            ImageUrl = "/images/cars/c300.jpg",
                            Model = "Mercedes-Benz C 300 4MATIC",
                            Price = 48500m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 2,
                            CreatedAt = new DateTime(2026, 2, 16, 9, 54, 45, 78, DateTimeKind.Utc).AddTicks(3044),
                            Description = "Шестото поколение E-Class. MBUX Superscreen, Burmester 4D звук, AIRMATIC окачване. Двигателят е 2.0L турбо с mild hybrid - 255 к.с. и 9-степенна автоматична скоростна кутия.",
                            EngineType = "2.0L Turbo Бензин + 48V Mild Hybrid",
                            Horsepower = 255,
                            ImageUrl = "/images/cars/e350.jpg",
                            Model = "Mercedes-Benz E 350 4MATIC",
                            Price = 64000m,
                            Year = 2025
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 4,
                            CreatedAt = new DateTime(2026, 2, 16, 9, 54, 45, 78, DateTimeKind.Utc).AddTicks(3047),
                            Description = "Един от най-мощните сериини AMG! 4-вратото купе има 4.0L V8 Biturbo който прави 630 к.с. + електромотор който добавя още 201 к.с. за обща мощност от 831 к.с. и над 1000 Nm. 0-100 за 2.8 сек. Има Drift Mode и AMG RIDE CONTROL+ окачване.",
                            EngineType = "4.0L V8 Biturbo + Електромотор (PHEV)",
                            Horsepower = 831,
                            ImageUrl = "/images/cars/amg-gt63s.jpg",
                            Model = "Mercedes-AMG GT 63 S E Performance",
                            Price = 215000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 5,
                            CreatedAt = new DateTime(2026, 2, 16, 9, 54, 45, 78, DateTimeKind.Utc).AddTicks(3050),
                            Description = "Флагманът на електрическата линия. Два мотора правейки 536 к.с. и 858 Nm със 118 kWh батерия и до 596 км пробег по WLTP. 56-инчов MBUX Hyperscreen идва стандартно. Бързо зареждане до 200 kW.",
                            EngineType = "Dual Motor Electric (AWD)",
                            Horsepower = 536,
                            ImageUrl = "/images/cars/eqs580.jpg",
                            Model = "Mercedes-Benz EQS 580 4MATIC",
                            Price = 128000m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 3,
                            CreatedAt = new DateTime(2026, 2, 16, 9, 54, 45, 78, DateTimeKind.Utc).AddTicks(3055),
                            Description = "Компактен SUV с мощност от 208 к.с. от малкият 2.0L турбо с 350NM и 7-степенна автоматична скоростна кутия. 0-100 за 7.2 сек. Висока позиция на шофиране, добра маневреност. Разход около 13.5л/100км в града.",
                            EngineType = "2.0L Turbo Бензин",
                            Horsepower = 208,
                            ImageUrl = "/images/cars/gla250.jpg",
                            Model = "Mercedes-Benz GLA 250 4MATIC",
                            Price = 35950m,
                            Year = 2019
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 6,
                            CreatedAt = new DateTime(2026, 2, 16, 9, 54, 45, 78, DateTimeKind.Utc).AddTicks(3056),
                            Description = "6.0L V12 Biturbo разполоага с 621 к.с. и 900NM. Ръчно изработен интериор, Executive задни седалки с масаж, Burmester High-End 4D, AIRMATIC и 4.5° задно управление. За 2026 има подгряване на коланите и Hot-Stone масаж.",
                            EngineType = "6.0L V12 Biturbo",
                            Horsepower = 621,
                            ImageUrl = "/images/cars/maybach-s680.jpg",
                            Model = "Mercedes-Maybach S 680 4MATIC",
                            Price = 340000m,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("SternGarage.Models.CarClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CarClasses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Спортен седан от средния клас",
                            Name = "C-Class"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Бизнес седан, комфорт и технологии",
                            Name = "E-Class"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Компактен SUV",
                            Name = "GLA"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Спортен автомобил, високопроизводителен",
                            Name = "AMG GT"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Електрически луксозен седан",
                            Name = "EQS"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ултра луксозни автомобили",
                            Name = "Maybach"
                        });
                });

            modelBuilder.Entity("SternGarage.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Reviews", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Мария Иванова",
                            CarId = 1,
                            Content = "Карам го от 6 месеца, MBUX-а е готин, седалките удобни. Разходът е около 7л извън града с mild hybrid-а. За тая цена е ок.",
                            CreatedAt = new DateTime(2023, 9, 12, 18, 30, 25, 0, DateTimeKind.Utc),
                            Rating = 4,
                            Title = "Добра кола за всеки ден"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Стоян Георгиев",
                            CarId = 1,
                            Content = "Имах W204 C350 с 3.5 V6 и беше страхотна кола - малка, бърза, луксозна. Сега новият C-Class е само 4-цилиндров, няма го вече онзи звук и характер. Да, технологията вътре е на ниво, MBUX е супер, но колата вече е само за хора които искат лукс отвътре, не за ентусиасти. AMG C63 с 4-цилиндров мотор е просто тъжно. Мерцедес избра да направи C-Class tech кола вместо шофьорска кола.",
                            CreatedAt = new DateTime(2024, 2, 5, 8, 7, 13, 0, DateTimeKind.Utc),
                            Rating = 2,
                            Title = "Къде отиде духът на C-Class?"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Никола Колев",
                            CarId = 3,
                            Content = "V8 плюс електромотор, на писта е брутално. Тежка е малко но с тия коне не се усеща чак толкова.",
                            CreatedAt = new DateTime(2024, 1, 13, 13, 30, 55, 0, DateTimeKind.Utc),
                            Rating = 5,
                            Title = "Звяр"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Елена Димитрова",
                            CarId = 4,
                            Content = "Колата е тиха и бърза, Hyperscreen-a е готин. Ама в България зарядната инфраструктура е зле, на магистралата няма почти нищо.",
                            CreatedAt = new DateTime(2026, 2, 10, 15, 43, 37, 0, DateTimeKind.Utc),
                            Rating = 3,
                            Title = "Добра но зарядните станции са проблем"
                        });
                });

            modelBuilder.Entity("SternGarage.Models.Car", b =>
                {
                    b.HasOne("SternGarage.Models.CarClass", "Class")
                        .WithMany("Cars")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("SternGarage.Models.Review", b =>
                {
                    b.HasOne("SternGarage.Models.Car", "Car")
                        .WithMany("Reviews")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("SternGarage.Models.Car", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SternGarage.Models.CarClass", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
